[logging]
debug = true
debug_sql = false

[database]
# One of (sqlite, postgres)
type = 'sqlite'

[database.sqlite]
path = './worblehat.sqlite'

[database.postgres]
host = 'localhost'
port = 5432
username = 'worblehat'
password = '/var/lib/worblehat/db-password' # path or plain text
name = 'worblehat'

# See https://flask.palletsprojects.com/en/2.3.x/config/
[flask]
TESTING = true
DEBUG = true
FLASK_ENV = 'development'
SECRET_KEY = 'change-me' # path or plain text

