[logging]
debug = true
debug_sql = false

[database]
# One of (sqlite, postgres)
type = 'sqlite'

[database.sqlite]
path = './worblehat.sqlite'

[database.postgres]
host = 'localhost'
port = 5432
username = 'worblehat'
password = '/var/lib/worblehat/db-password' # path or plain text
name = 'worblehat'

# See https://flask.palletsprojects.com/en/2.3.x/config/
[flask]
TESTING = true
DEBUG = true
FLASK_ENV = 'development'
SECRET_KEY = 'change-me' # path or plain text

[smtp]
enabled = false
host = 'smtp.pvv.ntnu.no'
port = 587
username = 'worblehat'
password = '/var/lib/worblehat/smtp-password'  # path or plain text
from = 'worblehat@pvv.ntnu.no'
subject_prefix = '[Worblehat]'

[deadline_daemon]
warn_days_before_borrow_deadline = [ "5", "1" ]
warn_days_before_expiring_queue_position_deadline = [ "3", "1" ]