"""initial_migration

Revision ID: 7dfbf8a8dec8
Revises:
Create Date: 2026-09-19 08:50:28.118662+02:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7dfbf8a8dec8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_author")),
    )
    with op.batch_alter_table("author", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_author_name"), ["name"], unique=True)

    op.create_table(
        "bookcase",
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_bookcase")),
    )
    with op.batch_alter_table("bookcase", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookcase_name"), ["name"], unique=True)

    op.create_table(
        "category",
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_category")),
    )
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_category_name"), ["name"], unique=True)

    op.create_table(
        "deadline_daemon_last_run_datetime",
        sa.Column("uid", sa.Boolean(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "uid = true", name=op.f("ck_deadline_daemon_last_run_datetime_`single_row_only`"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_deadline_daemon_last_run_datetime")),
    )
    op.create_table(
        "bookcase_shelf",
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("row", sa.SmallInteger(), nullable=False),
        sa.Column("column", sa.SmallInteger(), nullable=False),
        sa.Column("fk_bookcase_uid", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_bookcase_uid"],
            ["bookcase.uid"],
            name=op.f("fk_bookcase_shelf_fk_bookcase_uid_bookcase"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_bookcase_shelf")),
        sa.UniqueConstraint(
            "column", "fk_bookcase_uid", "row", name=op.f("uq_bookcase_shelf_column"),
        ),
    )
    op.create_table(
        "bookcase_item",
        sa.Column("isbn", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("amount", sa.SmallInteger(), nullable=False),
        sa.Column("fk_bookcase_shelf_uid", sa.Integer(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum(
                "board_game",
                "book",
                "comic",
                "movie",
                "video_game",
                name="mediatype",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.Enum(
                "aa",
                "ab",
                "ae",
                "af",
                "ak",
                "am",
                "an",
                "ar",
                "as",
                "av",
                "ay",
                "az",
                "ba",
                "be",
                "bg",
                "bh",
                "bi",
                "bm",
                "bn",
                "bo",
                "br",
                "bs",
                "ca",
                "ce",
                "ch",
                "co",
                "cr",
                "cs",
                "cu",
                "cv",
                "cy",
                "da",
                "de",
                "dv",
                "dz",
                "ee",
                "el",
                "en",
                "eo",
                "es",
                "et",
                "eu",
                "fa",
                "ff",
                "fi",
                "fj",
                "fo",
                "fr",
                "fy",
                "ga",
                "gd",
                "gl",
                "gn",
                "gu",
                "gv",
                "ha",
                "he",
                "hi",
                "ho",
                "hr",
                "ht",
                "hu",
                "hy",
                "hz",
                "ia",
                "id",
                "ie",
                "ig",
                "ii",
                "ik",
                "io",
                "is",
                "it",
                "iu",
                "ja",
                "jv",
                "ka",
                "kg",
                "ki",
                "kj",
                "kk",
                "kl",
                "km",
                "kn",
                "ko",
                "kr",
                "ks",
                "ku",
                "kv",
                "kw",
                "ky",
                "la",
                "lb",
                "lg",
                "li",
                "ln",
                "lo",
                "lt",
                "lu",
                "lv",
                "mg",
                "mh",
                "mi",
                "mk",
                "ml",
                "mn",
                "mr",
                "ms",
                "mt",
                "my",
                "na",
                "nb",
                "nd",
                "ne",
                "ng",
                "nl",
                "nn",
                "no",
                "nr",
                "nv",
                "ny",
                "oc",
                "oj",
                "om",
                "or",
                "os",
                "pa",
                "pi",
                "pl",
                "ps",
                "pt",
                "qu",
                "rm",
                "rn",
                "ro",
                "ru",
                "rw",
                "sa",
                "sc",
                "sd",
                "se",
                "sg",
                "si",
                "sk",
                "sl",
                "sm",
                "sn",
                "so",
                "sq",
                "sr",
                "ss",
                "st",
                "su",
                "sv",
                "sw",
                "ta",
                "te",
                "tg",
                "th",
                "ti",
                "tk",
                "tl",
                "tn",
                "to",
                "tr",
                "ts",
                "tt",
                "tw",
                "ty",
                "ug",
                "uk",
                "ur",
                "uz",
                "ve",
                "vi",
                "vo",
                "wa",
                "wo",
                "xh",
                "yi",
                "yo",
                "za",
                "zh",
                "zu",
                name="language",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_bookcase_shelf_uid"],
            ["bookcase_shelf.uid"],
            name=op.f("fk_bookcase_item_fk_bookcase_shelf_uid_bookcase_shelf"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_bookcase_item")),
    )
    with op.batch_alter_table("bookcase_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookcase_item_isbn"), ["isbn"], unique=True)
        batch_op.create_index(batch_op.f("ix_bookcase_item_name"), ["name"], unique=False)

    op.create_table(
        "borrowing",
        sa.Column("fk_bookcase_item_uid", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("due_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_bookcase_item_uid"],
            ["bookcase_item.uid"],
            name=op.f("fk_borrowing_fk_bookcase_item_uid_bookcase_item"),
        ),
        sa.PrimaryKeyConstraint("fk_bookcase_item_uid", "username", name=op.f("pk_borrowing")),
    )
    with op.batch_alter_table("borrowing", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_borrowing_username"), ["username"], unique=False)

    op.create_table(
        "borrowing_log",
        sa.Column("fk_bookcase_item_uid", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "borrowed", "renewed", "returned", name="borrowingeventtype", create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("due_time", sa.DateTime(), nullable=True),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(event_type = 'returned') = (due_time IS NULL)",
            name=op.f("ck_borrowing_log_`due_time_set_iff_not_returned`"),
        ),
        sa.ForeignKeyConstraint(
            ["fk_bookcase_item_uid"],
            ["bookcase_item.uid"],
            name=op.f("fk_borrowing_log_fk_bookcase_item_uid_bookcase_item"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_borrowing_log")),
    )
    with op.batch_alter_table("borrowing_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_borrowing_log_fk_bookcase_item_uid"),
            ["fk_bookcase_item_uid"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_borrowing_log_username"), ["username"], unique=False)
        batch_op.create_index(
            "ix_borrowinglog_item_user_uid",
            ["fk_bookcase_item_uid", "username", "uid"],
            unique=False,
        )

    op.create_table(
        "queue_position",
        sa.Column("fk_bookcase_item_uid", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("entered_queue_time", sa.DateTime(), nullable=False),
        sa.Column("notified_available_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_bookcase_item_uid"],
            ["bookcase_item.uid"],
            name=op.f("fk_queue_position_fk_bookcase_item_uid_bookcase_item"),
        ),
        sa.PrimaryKeyConstraint("fk_bookcase_item_uid", "username", name=op.f("pk_queue_position")),
    )
    with op.batch_alter_table("queue_position", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_queue_position_username"), ["username"], unique=False)

    op.create_table(
        "xref_item_author",
        sa.Column("fk_item_uid", sa.Integer(), nullable=False),
        sa.Column("fk_author_uid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_author_uid"], ["author.uid"], name=op.f("fk_xref_item_author_fk_author_uid_author"),
        ),
        sa.ForeignKeyConstraint(
            ["fk_item_uid"],
            ["bookcase_item.uid"],
            name=op.f("fk_xref_item_author_fk_item_uid_bookcase_item"),
        ),
        sa.PrimaryKeyConstraint("fk_item_uid", "fk_author_uid", name=op.f("pk_xref_item_author")),
    )
    op.create_table(
        "xref_item_category",
        sa.Column("fk_item_uid", sa.Integer(), nullable=False),
        sa.Column("fk_category_uid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fk_category_uid"],
            ["category.uid"],
            name=op.f("fk_xref_item_category_fk_category_uid_category"),
        ),
        sa.ForeignKeyConstraint(
            ["fk_item_uid"],
            ["bookcase_item.uid"],
            name=op.f("fk_xref_item_category_fk_item_uid_bookcase_item"),
        ),
        sa.PrimaryKeyConstraint(
            "fk_item_uid", "fk_category_uid", name=op.f("pk_xref_item_category"),
        ),
    )
    op.create_table(
        "queue_log",
        sa.Column("fk_bookcase_item_uid", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "joined",
                "left",
                "notified",
                "expired",
                "claimed",
                name="queueeventtype",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("fk_borrowing_log_uid", sa.Integer(), nullable=True),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(event_type = 'claimed') = (fk_borrowing_log_uid IS NOT NULL)",
            name=op.f("ck_queue_log_`borrowing_log_fk_set_iff_claimed`"),
        ),
        sa.ForeignKeyConstraint(
            ["fk_bookcase_item_uid"],
            ["bookcase_item.uid"],
            name=op.f("fk_queue_log_fk_bookcase_item_uid_bookcase_item"),
        ),
        sa.ForeignKeyConstraint(
            ["fk_borrowing_log_uid"],
            ["borrowing_log.uid"],
            name=op.f("fk_queue_log_fk_borrowing_log_uid_borrowing_log"),
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_queue_log")),
    )
    with op.batch_alter_table("queue_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_queue_log_fk_bookcase_item_uid"), ["fk_bookcase_item_uid"], unique=False,
        )
        batch_op.create_index(batch_op.f("ix_queue_log_username"), ["username"], unique=False)
        batch_op.create_index(
            "ix_queuelog_item_user_uid", ["fk_bookcase_item_uid", "username", "uid"], unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_log", schema=None) as batch_op:
        batch_op.drop_index("ix_queuelog_item_user_uid")
        batch_op.drop_index(batch_op.f("ix_queue_log_username"))
        batch_op.drop_index(batch_op.f("ix_queue_log_fk_bookcase_item_uid"))

    op.drop_table("queue_log")
    op.drop_table("xref_item_category")
    op.drop_table("xref_item_author")
    with op.batch_alter_table("queue_position", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_queue_position_username"))

    op.drop_table("queue_position")
    with op.batch_alter_table("borrowing_log", schema=None) as batch_op:
        batch_op.drop_index("ix_borrowinglog_item_user_uid")
        batch_op.drop_index(batch_op.f("ix_borrowing_log_username"))
        batch_op.drop_index(batch_op.f("ix_borrowing_log_fk_bookcase_item_uid"))

    op.drop_table("borrowing_log")
    with op.batch_alter_table("borrowing", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_borrowing_username"))

    op.drop_table("borrowing")
    with op.batch_alter_table("bookcase_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookcase_item_name"))
        batch_op.drop_index(batch_op.f("ix_bookcase_item_isbn"))

    op.drop_table("bookcase_item")
    op.drop_table("bookcase_shelf")
    op.drop_table("deadline_daemon_last_run_datetime")
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_name"))

    op.drop_table("category")
    with op.batch_alter_table("bookcase", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookcase_name"))

    op.drop_table("bookcase")
    with op.batch_alter_table("author", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_author_name"))

    op.drop_table("author")
    # ### end Alembic commands ###
